import { Octokit } from '@octokit/rest'
import axios from 'axios'
import { GeneratedApp } from '../codegen/service'

export interface DeploymentResult {
  repoUrl: string
  deploymentUrl: string
  vercelProjectId: string
}

export class DeploymentService {
  private octokit: Octokit
  private vercelToken: string

  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    })
    this.vercelToken = process.env.VERCEL_TOKEN || ''
  }

  async createGitHubRepository(
    name: string,
    description: string,
    isPrivate: boolean = true
  ): Promise<string> {
    try {
      const response = await this.octokit.repos.createForAuthenticatedUser({
        name: name.toLowerCase().replace(/\s+/g, '-'),
        description,
        private: isPrivate,
        auto_init: true,
      })

      return response.data.html_url
    } catch (error: any) {
      console.error('GitHub Repo Creation Error:', error.message)
      throw new Error('Failed to create GitHub repository')
    }
  }

  async pushCodeToGitHub(repoOwner: string, repoName: string, app: GeneratedApp): Promise<void> {
    try {
      // Get the default branch reference
      const { data: ref } = await this.octokit.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: 'heads/main',
      })

      const baseSha = ref.object.sha

      // Get the base tree
      const { data: baseCommit } = await this.octokit.git.getCommit({
        owner: repoOwner,
        repo: repoName,
        commit_sha: baseSha,
      })

      // Create blobs for each file
      const blobs = await Promise.all(
        app.files.map(async (file) => {
          const { data: blob } = await this.octokit.git.createBlob({
            owner: repoOwner,
            repo: repoName,
            content: Buffer.from(file.content).toString('base64'),
            encoding: 'base64',
          })
          return {
            path: file.path,
            mode: '100644' as const,
            type: 'blob' as const,
            sha: blob.sha,
          }
        })
      )

      // Add README
      const { data: readmeBlob } = await this.octokit.git.createBlob({
        owner: repoOwner,
        repo: repoName,
        content: Buffer.from(app.readme).toString('base64'),
        encoding: 'base64',
      })

      blobs.push({
        path: 'README.md',
        mode: '100644' as const,
        type: 'blob' as const,
        sha: readmeBlob.sha,
      })

      // Create a new tree
      const { data: newTree } = await this.octokit.git.createTree({
        owner: repoOwner,
        repo: repoName,
        tree: blobs,
        base_tree: baseCommit.tree.sha,
      })

      // Create a new commit
      const { data: newCommit } = await this.octokit.git.createCommit({
        owner: repoOwner,
        repo: repoName,
        message: 'Initial commit - Generated by ConvoToBuild',
        tree: newTree.sha,
        parents: [baseSha],
      })

      // Update the reference
      await this.octokit.git.updateRef({
        owner: repoOwner,
        repo: repoName,
        ref: 'heads/main',
        sha: newCommit.sha,
      })
    } catch (error: any) {
      console.error('GitHub Push Error:', error.message)
      throw new Error('Failed to push code to GitHub')
    }
  }

  async deployToVercel(
    projectName: string,
    gitUrl: string,
    envVars?: Record<string, string>
  ): Promise<{ projectId: string; deploymentUrl: string }> {
    try {
      // Create Vercel project
      const createProjectResponse = await axios.post(
        'https://api.vercel.com/v9/projects',
        {
          name: projectName.toLowerCase().replace(/\s+/g, '-'),
          gitRepository: {
            type: 'github',
            repo: gitUrl,
          },
          framework: 'nextjs',
          environmentVariables: envVars
            ? Object.entries(envVars).map(([key, value]) => ({
                key,
                value,
                target: ['production', 'preview', 'development'],
              }))
            : [],
        },
        {
          headers: {
            Authorization: `Bearer ${this.vercelToken}`,
            'Content-Type': 'application/json',
          },
        }
      )

      const projectId = createProjectResponse.data.id

      // Trigger deployment
      const deploymentResponse = await axios.post(
        'https://api.vercel.com/v13/deployments',
        {
          name: projectName.toLowerCase().replace(/\s+/g, '-'),
          gitSource: {
            type: 'github',
            repo: gitUrl,
            ref: 'main',
          },
        },
        {
          headers: {
            Authorization: `Bearer ${this.vercelToken}`,
            'Content-Type': 'application/json',
          },
        }
      )

      const deploymentUrl = `https://${deploymentResponse.data.url}`

      return {
        projectId,
        deploymentUrl,
      }
    } catch (error: any) {
      console.error('Vercel Deployment Error:', error.response?.data || error.message)
      throw new Error('Failed to deploy to Vercel')
    }
  }

  async getDeploymentStatus(deploymentId: string): Promise<string> {
    try {
      const response = await axios.get(`https://api.vercel.com/v13/deployments/${deploymentId}`, {
        headers: {
          Authorization: `Bearer ${this.vercelToken}`,
        },
      })

      return response.data.state // BUILDING, READY, ERROR, CANCELED
    } catch (error: any) {
      console.error('Deployment Status Error:', error.response?.data || error.message)
      throw new Error('Failed to get deployment status')
    }
  }

  async fullDeploy(
    projectName: string,
    description: string,
    app: GeneratedApp
  ): Promise<DeploymentResult> {
    try {
      // Step 1: Create GitHub repository
      const repoUrl = await this.createGitHubRepository(projectName, description)
      
      // Extract repo owner and name from URL
      const urlParts = repoUrl.split('/')
      const repoOwner = urlParts[urlParts.length - 2]
      const repoName = urlParts[urlParts.length - 1]

      // Step 2: Push code to GitHub
      await this.pushCodeToGitHub(repoOwner, repoName, app)

      // Step 3: Deploy to Vercel
      const { projectId, deploymentUrl } = await this.deployToVercel(projectName, repoUrl)

      return {
        repoUrl,
        deploymentUrl,
        vercelProjectId: projectId,
      }
    } catch (error: any) {
      console.error('Full Deploy Error:', error.message)
      throw error
    }
  }
}

export const deploymentService = new DeploymentService()
